package db;
// Generated 24.01.2014 10:16:50 by Hibernate Tools 3.6.0



/**
 * Langs generated by hbm2java
 */
public class Lang  implements java.io.Serializable {


     private Byte id;
     private String langcode;

    public Lang() {
    }

    public Lang(String langcode) {
       this.langcode = langcode;
    }
   
    public Byte getId() {
        return this.id;
    }
    
    public void setId(Byte id) {
        this.id = id;
    }
    public String getLangcode() {
        return this.langcode;
    }
    
    public void setLangcode(String langcode) {
        this.langcode = langcode;
    }




}


