package db;
// Generated 24.01.2014 10:16:50 by Hibernate Tools 3.6.0



/**
 * Locations generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer id;
     private String location;

    public Location() {
    }

    public Location(String location) {
       this.location = location;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }




}


