package db;
// Generated 24.01.2014 10:16:50 by Hibernate Tools 3.6.0



/**
 * Tags generated by hbm2java
 */
public class Tag  implements java.io.Serializable {


     private Integer id;
     private String tag;

    public Tag() {
    }

    public Tag(String tag) {
       this.tag = tag;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }




}


