package db;
// Generated 24.01.2014 10:16:50 by Hibernate Tools 3.6.0



/**
 * Tweetstotags generated by hbm2java
 */
public class TweetToTag  implements java.io.Serializable {


     private TweetToTagid id;

    public TweetToTag() {
    }

    public TweetToTag(TweetToTagid id) {
       this.id = id;
    }
   
    public TweetToTagid getId() {
        return this.id;
    }
    
    public void setId(TweetToTagid id) {
        this.id = id;
    }




}


