package db;
// Generated 24.01.2014 10:16:50 by Hibernate Tools 3.6.0



/**
 * TweetstotagsId generated by hbm2java
 */
public class TweetToTagid  implements java.io.Serializable {


     private long tweetid;
     private int tagid;

    public TweetToTagid() {
    }

    public TweetToTagid(long tweetid, int tagid) {
       this.tweetid = tweetid;
       this.tagid = tagid;
    }
   
    public long getTweetid() {
        return this.tweetid;
    }
    
    public void setTweetid(long tweetid) {
        this.tweetid = tweetid;
    }
    public int getTagid() {
        return this.tagid;
    }
    
    public void setTagid(int tagid) {
        this.tagid = tagid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TweetToTagid) ) return false;
		 TweetToTagid castOther = ( TweetToTagid ) other; 
         
		 return (this.getTweetid()==castOther.getTweetid())
 && (this.getTagid()==castOther.getTagid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getTweetid();
         result = 37 * result + this.getTagid();
         return result;
   }   


}


